### ISSUE TITLE
Always returns a random movie

### ISSUE THREAD

**Issue by alexscheitlin** [kwizapp/metadata-service#13]
**Expected Behaviour**
The service returns a random movie if no `imdbId` is specified, otherwise it returns the movie referenced by the provided id.

**Actual Behaviour**
The service always returns a random movie, not depending on whether an `imdbId` is given or not.

**Steps to Reproduce the Issue**
- Query the service with a specific `imdbId` (e.g., `tt0325980`).

**Comment by alexscheitlin** [comment]
The problem might be, that you use only one endpoint to return both
- a random movie (if no id is specified) or a specific movie (by imdbid)
- multiple random movies (one by default or n if specified) and exclude a move if an imdbid is given

Thus, if one wants a move with a specific id, your changes to serve multiple movies break the first query, as ecaxtly this movie is excluded.

=> Consider using two different endpoints.

**Comment by rschlaefli** [comment]
Actually, a specific movie should be returned (as can be seen in the e2e tests). The excluded movie is defined with a different parameter (`differentFrom`).

**Comment by alexscheitlin** [comment]
Resolved. The `id` parameter changed to `imdbId`.
