### ISSUE TITLE
Add prettier and eslint

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/metadata-service#7]
### Description

Add common prettier and eslint configs to project once https://github.com/kwizapp/kwiz/issues/28 is done.

### Tasks

- [x] configure prettier with shared config files
- [x] configure eslint with shared config files

**Comment by rschlaefli** [comment]
I have already installed prettier in #5 , but did not configure anything.

**Comment by nikzaugg** [comment]
> I have already installed prettier in #5 , but did not configure anything.

Yes, I will also open issues to configure prettier and eslint in all other projects. Thanks for the reminder.
